using Android.App;
using MvvmCross.Droid.Views;

namespace MusicRoadmap.Droid
{
    [Activity(Label = "Music Roadmap", NoHistory = false, MainLauncher = true, Icon = "@drawable/icon")]
    public class ArtistSearchView : MvxActivity
    {
        /// <summary>
        /// Use OnViewModelSet to inflate the view's ContentView from AXML.
        /// </summary>
        protected override void OnViewModelSet()
        {
            // This uses a resource identifier generated by Android to identify the view.
            SetContentView(Resource.Layout.View_Bill);
        }
    }
}