using Android.App;
using MvvmCross.Droid.Views;

namespace MusicRoadmap.Droid
{
    [Activity(Label = "Details")]
    class ArtistDetailsView : MvxActivity
    {
        protected override void OnViewModelSet()
        {
            // This uses a resource identifier generated by Android to identify the view.
            SetContentView(Resource.Layout.View_Details);
        }
    }
}