using Android.App;
using MvvmCross.Droid.Views;
using SQLite.Net;
using SQLite.Net.Platform.XamarinAndroid;
using System.IO;

namespace MusicRoadmap.Droid
{
    [Activity(Label = "Music Roadmap", NoHistory = false, MainLauncher = true, Icon = "@drawable/icon")]
    public class ArtistSearchView : MvxActivity
    {
        /// <summary>
        /// Use OnViewModelSet to inflate the view's ContentView from AXML.
        /// </summary>
        protected override void OnViewModelSet()
        {
            // This uses a resource identifier generated by Android to identify the view.
            SetContentView(Resource.Layout.View_Bill);


            var path = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "test.sqlite");
            var repository = new Repositories.MusicRepository(new SQLiteConnection(new SQLitePlatformAndroid(), path));
            repository.Create(new Model.Tag
            {
                id = 1,
                name = "fd",
                url = "fdf://fdf.d"
            });

            var r = repository.Get(1);

            int x = 0;

        }
    }
}